<?php

/**
 * @file
 *   An base module for for common functions that are used by
 *   the sub-modules enabling specific Amazon Web Services API for
 *   other Drupal modules.
 */

module_load_include('inc', 'aws');

/**
 * Implements hook_permission().
 * @return array An array of valid permissions for the aws module
 */
function aws_permission() {

  return array();
}

/**
 * Implements hook_menu().
 * @return array A menu api array for the module
 */
function aws_menu() {

  $items = array();

  return $items;
}

/**
 * Implementation admin_settings()
 * @return array A form api array of the admin setting
 */
function aws_admin_settings() {

  return system_settings_form($form);
}

/**
 * validate aws admin settings form
 * @param string $form_id
 * @param array $form_values
 */
function aws_admin_settings_validate($form_id, $form_values) {

  if (strlen($form_values['aws_accessKey']) !== 20) {

    form_set_error('aws_accessKey',    t('AWS access key ID must be 20 characters long.'));
  }
  if (strlen($form_values['aws_secret_key']) !== 40) {

    form_set_error('aws_accessKey',    t('AWS secret access key must be 40 characters long.'));
  }
}
